ALTER TABLE "ai_candidate_generation" ADD COLUMN "completion_reason" text;--> statement-breakpoint
ALTER TABLE "ai_candidate_generation" DROP CONSTRAINT "ai_candidate_generation_state_check";--> statement-breakpoint
ALTER TABLE "ai_candidate_generation" DROP CONSTRAINT "ai_candidate_generation_usage_check";--> statement-breakpoint
ALTER TABLE "ai_candidate_generation" DROP CONSTRAINT "ai_candidate_generation_result_check";--> statement-breakpoint
ALTER TABLE "ai_candidate_generation" DROP CONSTRAINT "ai_candidate_generation_state_facts_check";--> statement-breakpoint
ALTER TABLE "ai_candidate_generation" ADD CONSTRAINT "ai_candidate_generation_state_check" CHECK ("state" in ('created','queued','generating','frozen','abstained','failed','cancelled'));--> statement-breakpoint
ALTER TABLE "ai_candidate_generation" ADD CONSTRAINT "ai_candidate_generation_usage_check" CHECK ("input_tokens" between 0 and 1000000 and "output_tokens" between 0 and 100000 and "tool_call_count" between 0 and 5 and "model_turn_count" between 0 and 7);--> statement-breakpoint
ALTER TABLE "ai_candidate_generation" ADD CONSTRAINT "ai_candidate_generation_result_check" CHECK (("failure_code" is null or "failure_code" ~ '^[a-z_]{1,64}$') and (("state" = 'frozen' and "repair_candidate_id" is not null and "failure_code" is null and "completion_reason" = 'proposal_ready') or ("state" = 'abstained' and "repair_candidate_id" is null and "failure_code" is null and "completion_reason" = 'insufficient_evidence') or ("state" not in ('frozen','abstained') and "repair_candidate_id" is null and "completion_reason" is null)));--> statement-breakpoint
ALTER TABLE "ai_candidate_generation" ADD CONSTRAINT "ai_candidate_generation_state_facts_check" CHECK (("state" = 'created' and "queued_at" is null and "generation_started_at" is null and "completed_at" is null) or ("state" = 'queued' and "queued_at" is not null and "generation_started_at" is null and "completed_at" is null) or ("state" = 'generating' and "queued_at" is not null and "generation_started_at" is not null and "completed_at" is null) or ("state" in ('frozen','abstained','failed','cancelled') and "queued_at" is not null and "generation_started_at" is not null and "completed_at" is not null));--> statement-breakpoint
ALTER TABLE "ai_candidate_generation_event" DROP CONSTRAINT "ai_candidate_generation_event_state_check";--> statement-breakpoint
ALTER TABLE "ai_candidate_generation_event" DROP CONSTRAINT "ai_candidate_generation_event_transition_check";--> statement-breakpoint
ALTER TABLE "ai_candidate_generation_event" ADD CONSTRAINT "ai_candidate_generation_event_state_check" CHECK (("from_state" is null or "from_state" in ('created','queued','generating','frozen','abstained','failed','cancelled')) and "to_state" in ('created','queued','generating','frozen','abstained','failed','cancelled'));--> statement-breakpoint
ALTER TABLE "ai_candidate_generation_event" ADD CONSTRAINT "ai_candidate_generation_event_transition_check" CHECK (("from_state" is null and "to_state" = 'created') or ("from_state" = 'created' and "to_state" in ('queued','cancelled')) or ("from_state" = 'queued' and "to_state" in ('generating','cancelled')) or ("from_state" = 'generating' and "to_state" in ('frozen','abstained','failed','cancelled')));--> statement-breakpoint
CREATE OR REPLACE FUNCTION "guard_ai_candidate_generation_update"() RETURNS trigger AS $$
BEGIN
	IF TG_OP = 'DELETE' THEN RAISE EXCEPTION 'AI candidate generations are durable'; END IF;
	IF OLD."state" IN ('frozen','abstained','failed','cancelled') THEN RAISE EXCEPTION 'terminal AI candidate generations are immutable'; END IF;
	IF OLD."state" IS DISTINCT FROM NEW."state" AND NOT ((OLD."state" = 'created' AND NEW."state" IN ('queued','cancelled')) OR (OLD."state" = 'queued' AND NEW."state" IN ('generating','cancelled')) OR (OLD."state" = 'generating' AND NEW."state" IN ('frozen','abstained','failed','cancelled'))) THEN RAISE EXCEPTION 'invalid AI candidate generation transition'; END IF;
	IF ROW(OLD."ai_investigation_id",OLD."investigation_id",OLD."repair_run_id",OLD."baseline_id",OLD."workspace_id",OLD."github_repository_id",OLD."installation_id",OLD."base_commit_sha",OLD."profile_identity",OLD."provider_id",OLD."model_id",OLD."protocol_version",OLD."idempotency_key",OLD."created_at") IS DISTINCT FROM ROW(NEW."ai_investigation_id",NEW."investigation_id",NEW."repair_run_id",NEW."baseline_id",NEW."workspace_id",NEW."github_repository_id",NEW."installation_id",NEW."base_commit_sha",NEW."profile_identity",NEW."provider_id",NEW."model_id",NEW."protocol_version",NEW."idempotency_key",NEW."created_at") THEN RAISE EXCEPTION 'AI candidate generation authority is immutable'; END IF;
	IF OLD."queued_at" IS DISTINCT FROM NEW."queued_at" AND NOT (OLD."state" = 'created' AND NEW."state" = 'queued' AND OLD."queued_at" IS NULL AND NEW."queued_at" IS NOT NULL) THEN RAISE EXCEPTION 'AI candidate generation queue time is immutable'; END IF;
	RETURN NEW;
END;
$$ LANGUAGE plpgsql;
