import {
  AI_CANDIDATE_GENERATION_QUEUE,
  AI_INVESTIGATION_QUEUE,
  CANDIDATE_VERIFICATION_QUEUE,
  INVESTIGATION_CONTEXT_QUEUE,
  REPAIR_BASELINE_QUEUE,
  REPAIR_LOOP_QUEUE,
  REPAIR_PUBLICATION_QUEUE,
} from '../repair-runs/queue.ts';

export const canonicalRepairQueues = [
  AI_CANDIDATE_GENERATION_QUEUE,
  AI_INVESTIGATION_QUEUE,
  CANDIDATE_VERIFICATION_QUEUE,
  INVESTIGATION_CONTEXT_QUEUE,
  REPAIR_BASELINE_QUEUE,
  REPAIR_LOOP_QUEUE,
  REPAIR_PUBLICATION_QUEUE,
].sort() as readonly string[];
